### ISSUE TITLE
Missing cookies in version 0.7.2

### ISSUE THREAD

**Issue by arkadiusz-swierczek-pm** [harlan-zw/unlighthouse#100]
### Describe the bug

Version 0.7.2 introduced a bug where cookies aren't send on initial requests.

**unlighthouse.config**
``` 
export default {
  site: 'https://www.whatismybrowser.com',
  urls: [
    '/detect/what-http-headers-is-my-browser-sending',
  ],
  scanner: {
    device: 'desktop',
    skipJavascript: false,
  },
  cookies: [{
    name: 'AAA',
    domain: 'www.whatismybrowser.com',
    value: 'bbb',
  }]
};
```

Screenshot from version 0.7.1
![0 7 1](https://github.com/harlan-zw/unlighthouse/assets/109723953/0f037f95-e064-48fd-9d8e-adfbfb53e7c7)

Screenshot from version 0.7.2
![0 7 2](https://github.com/harlan-zw/unlighthouse/assets/109723953/9a7e853f-c095-4eee-9dc7-7d4380c97e78)

**Comment by harlan-zw** [comment]
Oops, thanks!
