### ISSUE TITLE
Mobile user agent is used for desktop scans

### ISSUE THREAD

**Issue by lutejka** [harlan-zw/unlighthouse#104]
### Describe the bug

When I set [scanner.device](https://unlighthouse.dev/api/config#scannerdevice) to desktop. A mobile user agent is used. 
For sites that do stuff based on the user agent, this might throw of the results...

![image](https://github.com/harlan-zw/unlighthouse/assets/22201189/54fd63b1-cc82-478f-847c-d91e8a429246)

### Reproduction

npx unlighthouse --site https://www.whatismybrowser.com/detect/what-is-my-user-agent/ --desktop

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 45.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Edge: 113.0.1774.42
    Firefox: 113.0
    Safari: 16.4
```

**Comment by harlan-zw** [comment]
Hey @lutejka, thanks for the issue :) 

This is fixed in 0.7.5, the user agents from the[ lighthouse constants](https://github.com/GoogleChrome/lighthouse/blob/main/core/config/constants.js#L77) will be used.
