### ISSUE TITLE
Add support for `sitemap.txt` format

### ISSUE THREAD

**Issue by adevade** [harlan-zw/unlighthouse#105]
### Clear and concise description of the problem

I would like to see support for `.txt` format of sitemaps. I know they are not as common, but they are damn useful for quick and small projects! 

What it is, is simply just a list of urls in a text file.

They are recognized by [Google](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#text), [Bing](https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed) and Yahoo (if the file is called `urllist.txt`, I think...).

[Read more about other valid sitemap formats here](https://sitemaps.org/protocol.html#otherformats)

### Suggested solution

I _guess_ it's as simple as adding a check for `sitemap.txt` in this function, and processing the URLs if found? Skipping the use of the `sitemapper` dependency in that case? Just reading line for line from the text file.

https://github.com/harlan-zw/unlighthouse/blob/fda3026e5908fd06ababf5b45f4dc907af53bfd9/packages/core/src/discovery/sitemap.ts#L9-L33

I'm not a JS dev (and definitely not a TS dev), but might be able to give it a try if no one else has the time. Please let me know if you would be willing to accept a PR for this.

**Something along the lines of this maybe?**

```diff
...

  for (let sitemapUrl of new Set(sitemaps)) {
    logger.debug(`Attempting to fetch sitemap at ${sitemapUrl}`)
    // make sure it's absolute 
    if (!sitemapUrl.startsWith('http'))
      sitemapUrl = withBase(sitemapUrl, site)

+    if (sitemapUrl.endsWith('.txt')) {
+      //
+      // logic here for getting each line to an item in an array
+      //
+    } else {
+      const { sites } = await sitemap.fetch(sitemapUrl)
+    }

    if (sites.length)
      paths = [...paths, ...sites]

    logger.debug(`Fetched sitemap with ${sites.length} URLs.`)
  }

...
```

### Additional context

Off topic: This is an incredible project! Super useful! Thank you! ❤️

**Comment by harlan-zw** [comment]
Oops, forget to say thanks for the suggestion @adevade! It was added in 0.7.5

**Comment by adevade** [comment]
Thanks! Tried it out last night actually! 😁 Works like a charm! 👍
