### ISSUE TITLE
Docs on how to run int programmatically?

### ISSUE THREAD

**Issue by AlEsGoGit** [harlan-zw/unlighthouse#106]
### Details

Hello!.
I need to launch lighthouse for ci purposes, so looking for documentation i got to this repo.
I think its amazing, but im having problems trying to use it as a part of a node module.
Am i missing something or theres is not docs about this topic?
It will be great.
Thank you!

Edit:
https://github.com/GoogleChrome/lighthouse/tree/main/docs/recipes/auth
Thats the reason.
I need to make a login in one web app and then audit the app while keep the login.

**Comment by harlan-zw** [comment]
Hi @AlEsGoGit, thanks for the issue :)

I've expanded the Authentication docs to include an authentication example, see [here](https://unlighthouse.dev/guide/guides/authentication#programmatic-usage).

Let me know if that's not clear or you have issues.

**Comment by harlan-zw** [comment]
Hmm I see. Personally I haven't ever needed this functionlity so have limited functionality and testing around it. I want to provide support for it. 

Would it be possible to provide a flow on the site you're trying to get authentication working for? Happy to create an account on it if needed.

**Comment by AlEsGoGit** [comment]
Im using laravel for my app, so the basic flow is a login page that redirects you to the requested page when you log in.
So when i provide an url, inside the "before go to" hook, i can use puppeteer to log in, but after that, puppeteer fails due to this redirect. 

`"Error "We have an error Error: the execution context was destroyed, probably because of a navigation."
`
Lighthouse solves this allowing you to pass a page instance that its already logged as a parameter for the lighthouse function:
[](https://github.com/GoogleChrome/lighthouse/tree/main/docs/recipes/auth)

Thats why i asked if there is an option to use unlighthouse inside a node script instead a cli command with an option file.
Somthing like this:
[](https://unlighthouse.dev/api)
But with the complete flow, to create an script that could make it work after doing something with puppeteer.
For example, i could make a previous request to log in, get the log in cookie form the request and provide it as an option to a callable unlighthouse.

I think this workaround will work for me.

But if you are instested in implementing a solution that works with the hook, i could make and provide you a basic example of the site.

Very thank you!

**Comment by harlan-zw** [comment]
Hey, sorry for the lack of response.

I've released 0.10.0 which includes an `authenticate` hook which should make this easier.

See here: https://unlighthouse.dev/guide/guides/authentication#programmatic-usage

Let me know if you have any issues.
