### ISSUE TITLE
Parsing primary & secondary sitemap.xml 

### ISSUE THREAD

**Issue by TitusRobyK** [harlan-zw/unlighthouse#108]
### Details

When I supply a website URL, the URL includes a sitemap.xml. Inside this sitemap.xml, there is a set of other sitemap.xml files. However, when I run the tool using this primary sitemap.xml, it doesn't appear to parse the secondary or Level II sitemap.xml files. Is this a bug or if this is not implemented yet ?

**Comment by harlan-zw** [comment]
Hi @TitusRobyK, thanks for the issue :)

As far as I know, this feature is working correctly. Are you able to share the site you're scanning?

Otherwise you can try running with `--debug` to see what's happening.

**Comment by TitusRobyK** [comment]
Hi @harlan-zw , It does not seem to work , 
Here is the command that i am trying 
This is the command that I am trying 
unlighthouse-ci --site anthemeap.com/sitemap.xml

**Comment by harlan-zw** [comment]
Hmm that's a lot of sitemaps! Likely causing the problem?
