### ISSUE TITLE
Feature request: add option to make unlighthouse-cli build-static assets have a relative path and use <base> tag

### ISSUE THREAD

**Issue by bux** [harlan-zw/unlighthouse#11]
Currently, all assets start with a slash
```html
<script type="module" crossorigin src="/assets/index.43945a3b.js"></script>
<link rel="modulepreload" href="/assets/vendor.58481f6a.js">
<link rel="stylesheet" href="/assets/index.5c5a87cc.css">
```
If one wants to host the content of the output folder in a subfolder that is not possible.
I've found the `routerPrefix` option, but that won't suffice.

**Comment by harlan-zw** [comment]
Hey @bux 

Thanks for taking the time to make an issue. 

What exactly is the issue with routerPrefix? I had created that configuration initially to solve this exact issue, as some integrations run from `/__unlighthouse/`.

**Comment by bux** [comment]
hi @harlan-zw 

i'm using this config for `unlighthouse-ci` with `--build-static`
```js
export default {
  site: "vite-starter-template.netlify.app",
  outputPath: "2022-04-07",
  routerPrefix: "lhk/2022-04-07",

  scanner: {
    device: "mobile",
    throttle: true,
  },
};
```

The results folder is being output to the subfolder `lhk` of the root project dir.
When running a node HTTP server (`serve`) from the root project dir and navigating to the the subfolder `lhk/2022-04-07` I can see some part of unlighthouse, but some assets fail to load and screenshots and reports don't seem to use the routerPrefix:


![image](https://user-images.githubusercontent.com/1235520/162161204-bf895d2d-cf5c-4e5a-8be1-a0cdc49f77f1.png)
![image](https://user-images.githubusercontent.com/1235520/162161267-202116e1-e81d-4e11-9b81-8af6f728e2b0.png)
![image](https://user-images.githubusercontent.com/1235520/162161306-b67d9b53-5976-46ec-90c1-9c9d8836c0da.png)

**Comment by harlan-zw** [comment]
Hey @bux 

This should be sorted in version 0.3.20. Let me know if you have any other issues :)

```
npx unlighthouse@0.3.21 --config-file <your-config> --build-static
```

**Comment by bux** [comment]
Awesome. I will take a look into it. Thanks

**Comment by bux** [comment]
@harlan-zw 

`unlighthouse/0.3.21 win32-x64 node-v16.14.0`

Does unlighthouse keep a build cache somewhere?
The index.[].js that is created contains an older prefix:
![image](https://user-images.githubusercontent.com/1235520/162683530-be5fcf3d-5372-4389-958e-77a9a013bf99.png)

**Comment by bux** [comment]
@harlan-zw do you know what happens here?
