### ISSUE TITLE
Determine urls using window.location

### ISSUE THREAD

**Issue by indykoning** [harlan-zw/unlighthouse#112]
### Clear and concise description of the problem

When proxying the unlighthouse frontend it will try to access the API and websocket routes using the localhost:port url still as this is still the url it is originally hosted on, causing issues as described in: https://github.com/indykoning/unlighthouse-docker/issues/1

### Suggested solution

I think the best solution would be to use placeholders for the url in the `payload.js` and replace these with the `window.location.origin` so it will use the url you accessed the frontend with.

### Alternative

An alternative is given in the respective issue by overwriting all the urls with that of the url you want
```js
  serverUrl: "http:/<site>/",
  clientUrl: "http://<site>/",
  apiUrl: "http://<site>/api",
  websocketUrl: "ws:///<site>/api/ws",
```
however this does not work if you can access the same unlighthouse instance from different urls

**Comment by harlan-zw** [comment]
Agreed! It shouldn't rely on hardcoded paths

**Comment by harlan-zw** [comment]
In 0.14.0 it will use relative paths when `routerPrefix` isn't configured.
