### ISSUE TITLE
Improved json format for the expandedJson

### ISSUE THREAD

**Issue by mastoj** [harlan-zw/unlighthouse#115]
### Clear and concise description of the problem

When first implementing the expandedJson I thought I was clever enough to not make it breaking in the future. However, I already think we should break the format. Today the json-file gets quite big, especially if you have a lot routes that you are processing. One reason is the duplication of data.

### Suggested solution

When generating the expandedJson report in the cli module we should have a format like this:

```
{
   summary: {
       categories: {
           "seo": { averageScore: 0.92 }
       },
       metrics: {
           "largest-contentful-paint": { averageNumericValue: 2133.23 }
       },
       ...
   },
   routes: {...},
   meta: {
       metrics: {
           "largest-contentful-paint": {
               "title": "Largest Contentful Paint",
               "description": "Largest Contentful Paint marks the time at which the largest text or image is painted. [Learn more](https://web.dev/lighthouse-largest-contentful-paint/)",
               "numericUnit": "millisecond",
           }
       },
       categories: {
           seo: {
               "title": "SEO,
           }
       }
    }
}
```

Here the metadata would only be present once instead of repeated for every value.

### Alternative

Keep as is, but then generating much more verbose json than needed. With that said, this verbose format makes it a little bit easier to read a single value since all you need to know is present in that place in the file.

**Comment by mastoj** [comment]
I just realized that with the above structure the actual values doesn't have to be an object, as long as the key of the values points to metadata.

**Comment by harlan-zw** [comment]
Happy to provide you with whichever changes you think are most appropriate. I'd say breaking changes are okay at this point.

Personally, I'm not too fussed about verbose reports as these JSON files should be consumed by code

**Comment by mastoj** [comment]
I realized it when I actually tried to use the output that it gets sort of verbose. With a more lightweight payload you can store the data in a db without any processing, which would be nice. 

I will make a stab at it and then you can decide if it better or not, it should be a quick fix.
