### ISSUE TITLE
Lighthouse version update

### ISSUE THREAD

**Issue by a-zivkovic** [harlan-zw/unlighthouse#124]
### Details

Hi, is there a plan to update Lighthouse to the latest version (v10)?

Keep up the awesome work 💪

**Comment by harlan-zw** [comment]
Hey :)

Yes! I have made 2 attempts to do so so far, unfortunately, there are a number of breaking changes with them dropping CJS support. 

Will stick with it and hope to release soon :crossed_fingers:

**Comment by millette** [comment]
I too would appreciate an upgrade (maybe v11?) since otherwise oklch colors fail, see <https://github.com/dequelabs/axe-core/issues/4007>.

**Comment by OmnomnomTee** [comment]
Have the same issue as @millette. I am using oklch colors for a website, which currently breaks the accessibility section of the report.

![Screenshot 2023-12-31 at 09 44 23](https://github.com/harlan-zw/unlighthouse/assets/18472607/0a2bbf38-565c-4136-9787-2c18521ab2ab)
