### ISSUE TITLE
Can I add cookies or things like that?

### ISSUE THREAD

**Issue by lirbre** [harlan-zw/unlighthouse#128]
### Details

First of all, loved unlighthouse. Cheers and thanks for such an usefull tool.

I'm working on a plataform that some pages have authentication and I was thinking if it would be possible do add my authentication cookies to the unlighthouse so I would make it run also with authentication and grasp the overall situation of my app also with the correct cookies.

I didn't found about it on documentation so I would love to get some info about that.

**Comment by harlan-zw** [comment]
Hey @lirbre, did you come across the [Authentication](https://unlighthouse.dev/guide/guides/authentication) docs page?

**Comment by lirbre** [comment]
Hey @harlan-zw. I didn't. Thanks for pointing out. :)
