### ISSUE TITLE
doesn't work when running on LAN server

### ISSUE THREAD

**Issue by jamaluddinrumi** [harlan-zw/unlighthouse#129]
### Describe the bug

i run it on my local development server with command below
```
#!/bin/bash

RANDOM=$(date +%s%N | cut -b10-19)

unlighthouse --site www.indomascot.com --urls /portofolio/,/cara-pemesanan/,/syarat-ketentuan/,/tentang-kami/ --mobile --no-cache --samples 2 --output-path ./Public/lh-reports/$(($RANDOM)) --debug
```

but i can not viewing the results properly via my development-laptop 
hint: look at can not make a connection to `WebSocket` message below
![Screen Shot 2023-05-31 at 7 29 42 AM](https://github.com/harlan-zw/unlighthouse/assets/446780/b20395cb-db3d-42c9-94c2-1fe9e72f1506)

here is the output generated by server
![Screen Shot 2023-05-31 at 7 34 11 AM](https://github.com/harlan-zw/unlighthouse/assets/446780/8a0e3fef-f3e7-482d-b22f-032c68a69ae2)

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 3.71 GB / 7.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.pnpm-store/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Chromium: 113.0.5672.126
```

**Comment by LucianVoju** [comment]
I think this is related to Chrome version. [Check this issue](https://github.com/GoogleChrome/lighthouse-ci/issues/886)
I managed to run it by setting _chrome.useSystem: false_ this will download an older version which works

**Comment by jamaluddinrumi** [comment]
> I think this is related to Chrome version. [Check this issue](https://github.com/GoogleChrome/lighthouse-ci/issues/886) I managed to run it by setting _chrome.useSystem: false_ this will download an older version which works

i'll check it out
thanks btw for your info

**Comment by hacknug** [comment]
> I managed to run it by setting chrome.useSystem: false this will download an older version which works

Thanks for the tip. This worked for me :+1:
