### ISSUE TITLE
Throttle desktop or add config to match Lighthouse

### ISSUE THREAD

**Issue by pedddro** [harlan-zw/unlighthouse#131]
### Clear and concise description of the problem

Currently, there is no solution to throttle the desktop connection to match [Lighthouse](https://github.com/GoogleChrome/lighthouse/blob/186e1804ae7757b6a975c9a8b8af1a5e9b67f81e/core/config/desktop-config.js#L15) one when running flag `--preset=desktop`.

This makes both LCP and CLS scores from the Performance category very different from field data. Take https://edition.cnn.com/ as an example:
Using Lighthouse @ 9.6.8:  LCP =2.5 sec CLS=0.045 sec 
Using UNLH desktop: LCP=0.8 sec CLS=0.005 sec
Using UNLH desktop throttled: LCP=11.4 sec CLS=0.005 sec
Field data from Desktop URL: LCP=2.07 sec CLS=0.08 sec

Also in [unlighthouse.dev/guide/guides/device](https://unlighthouse.dev/guide/guides/device#alias-enabledisable-throttling) you say "Unlighthouse will by default, throttle request to production sites for a more accurate performance score.", can you please clarify? 

### Suggested solution

Provide config, flag, or make the default desktop run the same throttling as LH.

**Comment by pedddro** [comment]
Creating a section in docs and adding recipes for performance-focused, SEO-focused runs would be better. CLS always may differ largely due to slight network conditions.

**Comment by harlan-zw** [comment]
The latest version should be a closer match to the PSI results. I agree docs can be improved on this, I will consider making a dedicated page. Feel free to make a new issue for what kind of things you'd like to see answered.
