### ISSUE TITLE
Add global query param

### ISSUE THREAD

**Issue by phihochzwei** [harlan-zw/unlighthouse#133]
### Clear and concise description of the problem

For our projects, we use Consent Management tools, which can be auto accepted by adding a query param.We also handle the preview mode of our pages in via a special query param. It would great if this could become part of the configuration and than added automatically to every route.

### Suggested solution

A property in the scanner-field like `"defaultQueryParam":"autoaccept=1"` (or any other string)

**Comment by harlan-zw** [comment]
Hey @phihochzwei, thanks for the suggestion :)

This is now available in v0.9.0, you can read the [release notes](https://github.com/harlan-zw/unlighthouse/releases/tag/v0.9.0) for guidance.

**Comment by phihochzwei** [comment]
Well, you are FAST :)

**Comment by phihochzwei** [comment]
Works like charm <3
