### ISSUE TITLE
Login Hook doesnt work 

### ISSUE THREAD

**Issue by paul1995tu** [harlan-zw/unlighthouse#137]
### Describe the bug

When I use  the Login Method from the Doku it gets executed 2 times. For example  admin@example.com' results in aaddmmiinn@@eexxaammppllee..ccoomm'. Same goes for Password
```
// unlighthouse.config.ts 
export default {
  puppeteerOptions: {
    // slow down slightly so input is not missed
    slowMo: 50,  
  },
  lighthouseOptions: {
    // allow storage to persist between pages
    disableStorageReset: true,
  },
  hooks: {
    'puppeteer:before-goto': async (page) => {
        // login to the page
      await page.goto('https://example.com/login')
      const emailInput = await page.$('input[type="email"]');
      await emailInput.type('admin@example.com');
      const passwordInput = await page.$('input[type="password"]');
      await passwordInput.type('password');
      await Promise.all([
        page.$eval('.login-form', form => form.submit()),
        page.waitForNavigation(),
      ]);
    },
  },
}
```

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.61 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /opt/homebrew/bin/node
    npm: 9.6.5 - /opt/homebrew/bin/npm

Iam using the default chromium thats get installed along  unlighthouse.
```

**Comment by rjohnep** [comment]
I have the same issue

**Comment by harlan-zw** [comment]
Hey @paul1995tu, thanks for the issue.

I'll be looking at this issue next time I'm on unlighthouse, hopefully within a few days.

**Comment by aguung** [comment]
I'm also having trouble using the Login Hook. Where when I have submitted the form there is no response at all until I get an error **Exception thrown when visiting route: Error: Navigation failed because the browser has disconnected!**. I've tried using the login function using puppeter directly, it can run normally. I even set the timeout in unlighthouse.config as below, it's still the same.
`page.setDefaultTimeout(300*1000)
page.setDefaultNavigationTimeout(300*1000)`

**Comment by harlan-zw** [comment]
Hi, in v0.10.0 I've introduced the `authenticate` hook that should solve this.

It works pretty much the same, except it will collect any localStorage or cookies after the authentication and share that with subequent browser sessions.

See here: https://unlighthouse.dev/guide/guides/authentication#programmatic-usage

**Comment by Dale-777** [comment]
@harlan does this hook also collect IndexedDB? our firestore key is placed here after login

 I am finding that if using 1 worker its is ok (but extremely slow), 3 workers and the state is unauthenticated.
