### ISSUE TITLE
Performance is different from Chrome reports

### ISSUE THREAD

**Issue by faludigabor** [harlan-zw/unlighthouse#142]
### Details

hi ,

we try to use unlighthouse to monitor the full site. It reports failry good performance however the client ran chrome's lighthouse and it reports different data.

Can you explain how could this happen please?

tx,
gabor

**Comment by dekristo** [comment]
Hi,

I noticed the same problem, I think that Unlighthouse doesn't use the latest google scoring :(

**Comment by harlan-zw** [comment]
v10 Lighthouse reports is planned, the blocker is they dropped `cjs` in this version and it creates issues with stubbing the package. 

Hopefully sorted soon!

**Comment by fahmij8** [comment]
any updates regarding this issue?

**Comment by fahmij8** [comment]
or maybe you can share the to do list
I would love to contribute if it's within my capacity
