### ISSUE TITLE
even if the url is already open, running unlighthouse again will open a new tab in the browser.

### ISSUE THREAD

**Issue by await-ovo** [harlan-zw/unlighthouse#15]
Hi, I want to use `unlighthouse` in my project's  `CI` stage, and when I run it locally with cli, I find that every time I execute `npx unlighthouse` it will open a new page in the browser, even though it was already opened with url `http://localhost:5678/`.

Maybe we can reuse the tab if the url is opened in browser(just activated it), similar to what happens in [react-scripts](https://github.com/facebook/create-react-app/tree/main/packages/react-scripts)?

If this is appropriate, it might be possible to reuse the code from [react-dev-utils ](https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openBrowser.js)directly. Instead of directly using [open](https://github.com/harlan-zw/unlighthouse/blob/main/packages/cli/src/cli.ts#L44)
> I'm also happy to create a pr :)

**Comment by harlan-zw** [comment]
Hey @await-ovo 

- Running in a ci mode requires you to use the `unlighthouse-ci` binary, there's documentation for that here: https://unlighthouse.dev/integrations/ci.html#introduction. There was an issue previously with the doc which I've just updated too 
- Good idea! I've implemented https://github.com/michaellzc/better-opn, doesn't seem like there's a solution for linux so I can't test it, so let me know if it's working as expected
