### ISSUE TITLE
Not all links on page detected

### ISSUE THREAD

**Issue by BennyAlex** [harlan-zw/unlighthouse#154]
### Describe the bug

Hello,
When I scan the page https://audit.zugang4all.de/ with crawl enabled, I only get the report for the / and /contact page. 
All links on the top are ignored.
Here is my config.

```

/// <reference types="unlighthouse" />
import { defineConfig } from 'unlighthouse'

export default defineConfig({
  site: 'https://audit.zugang4all.de/',
  debug: true,
  cache: false, // disable caching of results
  scanner: {
    maxRoutes: 500, // max number of routes to scan
    samples: 2, // number of samples to take
    crawler: true, // enable the crawler
    robotsTxt: false, // don't respect robots.txt
    sitemap: false, // don't respect sitemap.xml,
    // exclude all pdfs and amp pages
    exclude: [
      '/.*?pdf',
      '.*/amp',
      /* 'en-*',*/
    ],
    // use desktop to scan
    device: 'desktop',
    // enable the throttling mode, good for getting more consistent results
    throttle: false,
  },
  chrome: {
    useSystem: false, // use the bundled chrome,
  },
  puppeteerOptions: {
    headless: true, // headless works best
  }
})
```

### System / Nuxt Info

```Shell
Win 11, bundled chromium, node 18
```

**Comment by levino** [comment]
I have a similar issue. Looks like unlighthouse does not find certain links. What do do?

**Comment by BennyAlex** [comment]
> I have a similar issue. Looks like unlighthouse does not find certain links. What do do?

I probably use something else (eg playwright and lighthouse by myself.)
Most of the reported performance metrics are way of / to low in comparison with page speed insights or running lighthoues by myself

**Comment by harlan-zw** [comment]
Seems like something on your end is blocking Unlighthouse's crawler. I don't think there's anything I can do on my end sorry.
