### ISSUE TITLE
Just saying thank you for this tool!

### ISSUE THREAD

**Issue by alphex** [harlan-zw/unlighthouse#156]
### Details

This tool is fantastic, thank you for the work.

As an aside, this is the first application that has maxed out the CPU cores on my M1 Max with 64GB of ram...  To the point that the fans even turned on,  I'm honestly not sure if I've heard them spin up befeore.

That in its self is an acheivement that I appreciate!

**Comment by harlan-zw** [comment]
Haha, thank you! Appreciate your kind words.

I loved this issue so much that I posted it on Twitter https://twitter.com/harlan_zw/status/1692825156228403448
