### ISSUE TITLE
unlighthouse-ci --site  ${SITE} --static-site failes to result in a static offline site that is not root relative

### ISSUE THREAD

**Issue by DoctorOgg** [harlan-zw/unlighthouse#157]
### Describe the bug

unlighthouse-ci --site  ${SITE} --static-site

Seems to be completely broken.

**Comment by harlan-zw** [comment]
Hi, I'm not sure where you got this flag from `--static-site`, the flag should be `--build-static`

**Comment by DoctorOgg** [comment]
yah thanks for that, not sure where I got it from either
