### ISSUE TITLE
unlighthouse configs interchangeable with unlighthouse-ci?

### ISSUE THREAD

**Issue by DoctorOgg** [harlan-zw/unlighthouse#158]
### Details

I would have thought the configs are interchangeable, however the ci tool seems to ignore seeings like the list of url's  and scanner options.

```  scanner: {
    sitemap: false,
    crawler: false,
    device: 'desktop',
    samples: 1,
    throttle: false,
    dynamicSampling: false,
  }
```

Thank you for your help

**Comment by DoctorOgg** [comment]
ok, if I resort to not using a config file I can get the ci tool to only check specific urls, it would be nice to be able to use a config file here. 

```
unlighthouse-ci --site https://example.com --disable-sitemap --desktop --samples 1 --throttle --build-static --reporter jsonExpanded --urls /templates/,/courses-learning/,/software/
```

**Comment by mountainash** [comment]
Hmmm - the [documentation states](https://unlighthouse.dev/integrations/cli#configuration) both ways should work.

I can get `unlighthouse-ci` using the `unlighthouse.config.ts` file for configuration, but I have to set the `site: <URL>` entry in the file.

npx unlighthouse-ci --config unlighthouse.config.ts

_Running unlighthouse/0.10.0 darwin-arm64 node-v20.5.1__

Your initial post isn't showing your full config, but most of your keys should be inside a parent `scanner: {` object.

**Comment by DoctorOgg** [comment]
Yah, I tried the simplest of configs, and nothing worked,  resorted to command line switches, also on a separate note, when using under docker, the remove dir behavior and recreate really messes with volume binds with docker and permissions. but yah.... The tool could use some refinement, as well as better debugging output.
