### ISSUE TITLE
Skip JavaScript flag ignored

### ISSUE THREAD

**Issue by Bjortin** [harlan-zw/unlighthouse#170]
### Describe the bug

I've been trying to use both the CLI and CI approach, with and without configuration files, and JavaScript is not disabled regardless of file configuration or flags.

**(JavaScript content is rendered despite this flag)**
--disable-javascript 

**(JavaScript content is rendered despite this property of the scanner)**
scanner.skipJavascript = ture

**Comment by harlan-zw** [comment]
This flag is used to allow the crawler to work with SPAs, it's disabled by default and does work.

Can you provide some more context on why you want it disabled and I can give you some idea of what you're looking for? FWIW it's not possible to run Lighthouse with js disabled.
