### ISSUE TITLE
Cookies are missing during lighthouse scan

### ISSUE THREAD

**Issue by lutejka** [harlan-zw/unlighthouse#197]
### Describe the bug

I set some cookies in the configuration.  During the startup, those cookies are used, however they are missing in the actuall scan. 

To heck this, I used the following set up: 
 
 server.js

```
import http from 'http'

function parseCookies (request) {
    const list = {};
    const cookieHeader = request.headers?.cookie;
    if (!cookieHeader) return list;

    cookieHeader.split(`;`).forEach(function(cookie) {
        let [ name, ...rest] = cookie.split(`=`);
        name = name?.trim();
        if (!name) return;
        const value = rest.join(`=`).trim();
        if (!value) return;
        list[name] = decodeURIComponent(value);
    });

    return list;
}

const server = http.createServer(function (request, response) {
    // To Read a Cookie
    const cookies = parseCookies(request);
    console.log(cookies)


    response.writeHeader(200, {"Content-Type": "text/html"});
    response.write('<div>test</div>');
    response.end();
}).listen(8080);

const {address, port} = server.address();
console.log(`Server running at http://${address}:${port}`);
```

run ´node server.js´

run unlghthouse with the follwoing config 

```
export default {
  site: 'http://localhost:8080',
  cookies: [
    {
      name: 'test',
      value:'2023-07-06T12:01:40.453Z'
    },
  ],
}
```

In the output of `node server.js` the used cookies should be logged, but they are missing.

**Comment by harlan-zw** [comment]
Hi, thanks for providing the reproduction code. I've tried it locally and it seems to be outputting the headers. Can you confirm which version you're using?

**Comment by lukas-matejka-scayle** [comment]
I cant remember it was either 0.10.* or 0.11*. I also just tested it with 0.12.0 and it still happens 


![image](https://github.com/harlan-zw/unlighthouse/assets/150658033/627f02c6-8848-4c69-8a5e-1fc8b6d900a4)

**Comment by lutejka** [comment]
I cant remember it was either 0.10.* or 0.11*. I also just tested it with 0.12.0 and it still happens


![image](https://github.com/harlan-zw/unlighthouse/assets/22201189/e0f920f8-5bc0-4902-aa28-007f8d3c5214)

**Comment by lutejka** [comment]
When testing a other side I also got these errors a bunch 

```
 ERROR  Failed to set cookies Protocol error (Network.deleteCookies): Target closed                                                                                                                      Unlighthouse 10:38:48 PM

  at CallbackRegistry.clear (/Users/lukas.matejka/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
  at CdpCDPSession._onClosed (/Users/lukas.matejka/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:98:25)
  at Connection.onMessage (/Users/lukas.matejka/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:118:25)
  at Immediate.<anonymous> (/Users/lukas.matejka/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:37:36)
  at process.processImmediate (node:internal/timers:478:21)
```

**Comment by criisv7** [comment]
Facing the same issue. Is there a fix for it in place or any bypass. @harlan-zw

**Comment by olivoil** [comment]
I am seeing the same error message

`ERROR  Failed to set cookies Protocol error (Network.deleteCookies): Target closed`

**Comment by harlan-zw** [comment]
So the issue with this error is that it's trying to deleteCookies _after_ it has closed the tab. This can happen when the tab fails to initially open.

In v0.12.0 we have a soft error handler on this as it should be fine to fail.

If someone can provide a reproduction then I can investigate this further otherwise will need to close for now as cookies _can_ be set.
