### ISSUE TITLE
Static reports 404 on sub-reports and thumbnails as `/reports` (leading slash) is hardcoded somewhere in `_ctx.report.artifactUrl`

### ISSUE THREAD

**Issue by AshSimmonds** [harlan-zw/unlighthouse#201]
### Describe the bug

Only been playing with it an hour or so, can't pinpoint exactly where yet, but when you deploy a static site that's in a sub-directory, some of the thumbnails and all the individual page reports have the URL beginning with `/reports/`, which refers back to `example.com/reports/unlighthouse-report/the-file`, instead of `example.com/unlighthouse-report/reports/the-file`.  
  
![screenshot_20240408-042746](https://github.com/harlan-zw/unlighthouse/assets/9034041/3fe99b7c-0b4f-4dba-a74b-62c006d782aa)

![screenshot_20240408-042838](https://github.com/harlan-zw/unlighthouse/assets/9034041/5a35342e-02d7-4693-b2ac-664b7a32b1a2)

What's attempting to be fetched:  
- `https://mayfairfinanceaustralia.com/reports/businessfinance/screenshot.jpeg`

Actual URL example:  
- `https://mayfairfinanceaustralia.com/seo/reports/20240408_0243/reports/businessfinance/screenshot.jpeg`

**Comment by AshSimmonds** [comment]
Update: the issue is in the `payload.js` file, I just did a find/replace for `artifactUrl":"/reports` to remove the leading slash and everything works, so wherever that initial generation comes from.

**Comment by harlan-zw** [comment]
Hi, I think you might want the `routerPrefix` optin? https://unlighthouse.dev/api/config#routerprefix

**Comment by harlan-zw** [comment]
In 0.14.0 relative paths are used when routerPrefix isn't configured which should solve this.
