### ISSUE TITLE
Puppeteer getting `protocolTimeout`

### ISSUE THREAD

**Issue by AshSimmonds** [harlan-zw/unlighthouse#202]
### Describe the bug

```
file:///usr/local/lib/node_modules/@unlighthouse/cli/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89
    #error = new ProtocolError();
             ^

ProtocolError: Page.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
```  
  
I don't know whether it's tripping up on a certain page, the debug log only tells you what page it was working on after success of `runLighthouseTask`. Not sure if the page itself matters, it keeps getting to about 62% then crapping out.

### Reproduction

`unlighthouse-ci --site ashsimmonds.com --build-static`

**Comment by harlan-zw** [comment]
Hi, can you please try v0.12.0. It _might_ resolve this issue.

**Comment by thidayatullah** [comment]
@harlan-zw 
I'm using v0.12.0 and still have the same problem

**Comment by robpetrin** [comment]
Can confirm this issue persists in v0.12.1 when using `npx unlighthouse --site [url] --desktop --reporter csvExpanded`

**Comment by harlan-zw** [comment]
You can try [v0.12.2](https://github.com/harlan-zw/unlighthouse/releases/tag/v0.12.2) but not sure if it will help exactly
