### ISSUE TITLE
CI scan randomly failing with NodeJS error

### ISSUE THREAD

**Issue by ivanmihaljevicdiageo** [harlan-zw/unlighthouse#204]
### Describe the bug

I'm deploying Vercel projects using ADO pipeline and then scanning those deployments with Unlighthouse. Since version 0.11.0, I've encountered issue that randomly occurs across various projects and sites. Even when the code and content remain unchanged, scans sometimes fail or pass unpredictably.

Sometimes, after the scan identifies all paths that don't meet budget limits, it randomly fails with a Node error. I've tested it with multiple Node versions, but didn't notice any pattern.
![2](https://github.com/harlan-zw/unlighthouse/assets/146820748/11d82adf-6746-4eef-80ab-5ee15e1bd3f6)

**Comment by harlan-zw** [comment]
This should hopefully be fixed in [v0.11.6](https://github.com/harlan-zw/unlighthouse/releases/tag/v0.11.6)
