### ISSUE TITLE
Static Report has broken full size images on performance tab

### ISSUE THREAD

**Issue by Dale-777** [harlan-zw/unlighthouse#208]
### Describe the bug

1. Generate report
2. Open the Performance Tab
3. click any thumbnail 

The issue can be seen here: https://inspect.unlighthouse.dev/

Error seen in the console:

`index.459f7752.js:7106 There are no focusable elements inside the <FocusTrap />`

<img width="1728" alt="Screenshot 2024-04-17 at 10 57 41" src="https://github.com/harlan-zw/unlighthouse/assets/77000850/9d1acfc3-2af4-409b-aade-0a2f592d5a52">

**Comment by harlan-zw** [comment]
I did attempt to debug this without much success, not sure what the issue is exactly. I don't think it relates to the FocusTrap warning.

I think this will need to wait until I re do the UI.

**Comment by harlan-zw** [comment]
This _seems_ to have fixed itself.
