### ISSUE TITLE
ERR_MODULE_NOT_FOUND @unlighthouse/client

### ISSUE THREAD

**Issue by flortsch** [harlan-zw/unlighthouse#21]
### Describe the bug

I am getting the following error when trying to run unlighthouse with yarn.

```
file:///home/flortsch/Projekte/bytegrasp/website/.yarn/cache/mlly-npm-0.4.3-bf0f735108-d9d50babe7.zip/node_modules/mlly/dist/index.mjs:4699
  return pcall$1(resolvePathSync$1, id, opts);
         ^

Error: Error: Cannot find module @unlighthouse/client imported from file:///home/flortsch/Projekte/bytegrasp/website/.yarn/__virtual__/@unlighthouse-core-virtual-0e58d5d01f/0/cache/@unlighthouse-core-npm-0.3.29-68f89b983a-18c2ef2835.zip/node_modules/@unlighthouse/core/dist/index.mjs
    at resolvePath$1 (file:///home/flortsch/Projekte/bytegrasp/website/.yarn/cache/mlly-npm-0.4.3-bf0f735108-d9d50babe7.zip/node_modules/mlly/dist/index.mjs:4699:10)
    at ctx.setServerContext (file:///home/flortsch/Projekte/bytegrasp/website/.yarn/__virtual__/@unlighthouse-core-virtual-0e58d5d01f/0/cache/@unlighthouse-core-npm-0.3.29-68f89b983a-18c2ef2835.zip/node_modules/@unlighthouse/core/dist/index.mjs:5732:33)
    at run (file:///home/flortsch/Projekte/bytegrasp/website/.yarn/cache/@unlighthouse-cli-npm-0.3.29-c6be2d1d24-26f2fe047e.zip/node_modules/@unlighthouse/cli/dist/cli.mjs:27:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.7.0
```

I installed unlighthouse as dev dependency in our project. Also manually installing the module @unlighthouse/client that seems to be missing as dev dependency did not help. Any ideas? Could it be related to yarn pnp?

**UPDATE:** It indeed looks like it's related to yarn. Running unlighthouse in my project with npx works.

### Reproduction

```
yarn unlighthouse --site http://localhost:1234
```

### System Info

```Shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 22.75 GB / 30.59 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 3.2.2 - /usr/bin/yarn
    npm: 8.17.0 - /usr/bin/npm
  Browsers:
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @flortsch 

Thank you for the detailed issue. I'll be looking at v1 of Unlighthoue maybe next month and have included this issue as part of the development. 

If you can think of a quick fix around it before I can look at it then, please let me know :)
