### ISSUE TITLE
"Lighthouse failed to run performance audits for "/", adding back to queue." , in order to find the cause of the problem

### ISSUE THREAD

**Issue by OSnuszka** [harlan-zw/unlighthouse#213]
### Details

I use Unlighthouse to scan production domains, and some of them are not scannable due to this error appearing in the logs.
This error is looping during execution:
`"Lighthouse failed to run performance audits for "/", adding back to queue."`

I'm using unlighthouse-ci to execute my audits.
Below my configuration:
```
/// <reference types="unlighthouse" />
export default ({
  puppeteerClusterOptions: {
    chrome: {
      useSystem: false
    },
    maxConcurrency: 1,
  },
  
  puppeteerOptions: {
    headless: true,
    args: ["--no-sandbox"],
    },
  server: {
    open: true,
  },

  site: "some url here",
  scanner: {
    device: "desktop",
    skipJavascript: false,
    robotsTxt: false,
    sitemap: false,
    crawler: false,
    samples: 10,
    setTimeout: 60000,
    
  },
  debug: false,
  
});

```

**Comment by harlan-zw** [comment]
The error occurs from the lighthouse binary. Lighthouse itself does not expose any information on why it failed so not too sure what the solution is.

You can try and earlier version of Unlighouse which used a lighthouse version that didn't throw this issue as often.

**Comment by Dale-777** [comment]
is setTimeout an option for Scanner?

**Comment by OSnuszka** [comment]
> is setTimeout an option for Scanner?

to be honest, I noticed this timeout not work as expected, but I keep that in configuration anyway (It was a try to fix problem described in this ticket)

**Comment by raphaelbernhart** [comment]
Is there any update on this issue? :)

**Comment by harlan-zw** [comment]
This should be triggered less frequently in more recent versions, I don't think there's anything else I can do on my end. 

If you can reliably replicate it though please send through details.
