### ISSUE TITLE
Add support for LHCI basic auth

### ISSUE THREAD

**Issue by tiagosv** [harlan-zw/unlighthouse#214]
### Clear and concise description of the problem

I'm using a private LHCI and it has basic auth set up, which means I can't use the LHCI functionality offered by this app.
It would be great to add two extra optional CLI/CI params for username and password.

### Suggested solution

Add two new cli params:

```
cli.option('--lhci-user <lhci-user>', 'Basic auth username of your LHCI server.')
cli.option('--lhci-user <lhci-pass>', 'Basic auth password of your LHCI server.')
```

Of course there's more changes needed, but this was to exemplify more clearly what I'm talking about.

**Comment by harlan-zw** [comment]
This should now be possible in [v0.12.2](https://github.com/harlan-zw/unlighthouse/releases/tag/v0.12.2) using `--lhci-auth username:password`
