### ISSUE TITLE
Mismatch between test site url and x-default causes no pages to be scanned

### ISSUE THREAD

**Issue by will-me** [harlan-zw/unlighthouse#215]
### Describe the bug

When site url is different from x-default url, tests fail to run. 

**Scenario**
Test site url is: "https://testing.brand-mg4kapdsn.vercel.app/en-us/products"
x-default value is: "https://preprod.brand.com/en-us/products"

Test is ignored and logs out:
```
[debug] [Unlighthouse] HTML extract of 'https://testing.brand-mg4kapdsn.vercel.app/en-us/products' response succeeded. 
[debug] [Unlighthouse] Page has an alternative lang, ignoring '/en-us/products': 'https://preprod.brand.com/en-us/products'
[debug] [Unlighthouse] Ignoring route '/en-us/products'.
```

This is using a supplied list of urls _not_ using the site crawler.

**Comment by adamkoppede** [comment]
Sound like the behavior documented for [`scanner.ignoreI18nPages = true`](https://unlighthouse.dev/api/config#scannerignorei18npages), which is the default. Setting it to `false` worked for me, when I also provided an explicit list of URLs.

**Comment by will-me** [comment]
@adamkoppede Yes you are correct, setting this to false _did_ fix the issue. However we have dozens (and eventually hundreds) of pipelines that need to run this config. Setting this to false on a site with 15 locales will slow down the pipelines too much.

**Comment by harlan-zw** [comment]
Thanks @adamkoppede, I've pushed up a fix so that it warns users and points them to this config the first time.

@will-me I'd suggest disabling i18n and using the `include` / `exclude` rules to only test one locale if that's your intention.
