### ISSUE TITLE
Usage on a self-hosted server?

### ISSUE THREAD

**Issue by GalacticHypernova** [harlan-zw/unlighthouse#221]
### Details

From what it seems, unlighthouse is only usable in localhost, since it attempts to access localhost:5678/api/scan-meta. Is it possible to use it on an external server?
For example, imagine a web app that is running on an ubuntu server. I would like to unlighthouse it, but since I already have ownership of the server I would like to get the reports from that server. Is there a way to make unlighthouse use the correct address or is it always localhost?

**Comment by YannickFuereder** [comment]
if you start unlighthouse on the same server as your web app and set up a simple reverse proxy everything should be working just fine

**Comment by GalacticHypernova** [comment]
@YannickFuereder thanks for the reply! I already solved this, simply forgot to close, my apologies, but thanks again!
