### ISSUE TITLE
Bump ws to 8.17.1

### ISSUE THREAD

**Issue by jbouder** [harlan-zw/unlighthouse#226]
### Describe the bug

The current version of `ws` utilized by lighthouse core is affected by the following vulnerability: _DoS when handling a request with many HTTP headers_

Requesting an update to this dependency to the latest version of `8.17.1`. I would also be interested in creating a PR to resolve the vulnerability myself. If that makes sense, can you provide any specific guidance on next steps? Thanks!

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. I've just pushed out a release with bumped deps.

**Comment by jbouder** [comment]
> Hi, thanks for the issue. I've just pushed out a release with bumped deps.

That did it, thanks!
