### ISSUE TITLE
How to set Rate Limit?

### ISSUE THREAD

**Issue by albilu** [harlan-zw/unlighthouse#228]
### Details

Is there a way to set a rate limit like max 20 requests/minutes to avoid 429 Too Many requests on a prod site?

**Comment by pedddro** [comment]
try: https://unlighthouse.dev/guide/recipes/improving-accuracy#reduce-parallel-scans

**Comment by albilu** [comment]
> try: https://unlighthouse.dev/guide/recipes/improving-accuracy#reduce-parallel-scans

works. thanks

**Comment by productdevbook** [comment]
Resolved by v1 — auditor strategies now ship weighted + rate-limited picks (commit 0e1879c). Configure via `auditor.router` in your config. Tracking v1 release in #349. Closing; please reopen if this still reproduces against v1.
