### ISSUE TITLE
Remove FID column on Performance tab

### ISSUE THREAD

**Issue by pedddro** [harlan-zw/unlighthouse#229]
### Details

[FID will be sunset in favor of INP](https://web.dev/blog/inp-cwv-march-12), which is only available on other lighthouse modes, not the one used in UNLH.

**Comment by harlan-zw** [comment]
Thanks for the issue and sorry for the delay.

I agree it _should_ be replaced with INP but there's no reliable way to test INP in a lighthouse environment without the end-users providing a bunch of potentially confusing config.

For now, I'll just add a warning icon on this column letting people know it's deprecated.

![image](https://github.com/user-attachments/assets/4fcf9510-b6b8-49e4-a5fe-eb6df2f4fa6a)

In v1 I hope to support other modes OR hook into using CrUX data for each route.

**Comment by harlan-zw** [comment]
TBT is already shown, ideally I have something to replace it

**Comment by pedddro** [comment]
> TBT is already shown, ideally I have something to replace FID

I don't understand why you need to have something to replace FID.

No one used it and the passing rate was +95% before the deprecation.

**Comment by harlan-zw** [comment]
just to make the columns evenly spaced :+1:
