### ISSUE TITLE
Name of report

### ISSUE THREAD

**Issue by loqimean** [harlan-zw/unlighthouse#234]
### Details

Would be fine to get name for reports, like I'd like to have only two, like certain `.unlighthouse/mobile` and `.unlighthouse/mobile`, so, now I have something like: `.unlighthouse/mobile/website.com/wdfw23df`. Can you help me with that?

**Comment by harlan-zw** [comment]
Hi, thanks for the issue.

This is quite simple, just run it using the `--output-path` command. So to generate for mobile and desktop you would have.

```bash
unlighthouse-ci --output-path .unlighthouse/mobile  --mobile --site <site>
unlighthouse-ci --output-path .unlighthouse/desktop -- desktop --site <site>
```
