### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by nicooprat** [harlan-zw/unlighthouse#3]
Hi there,

Just trying Unlighthouse for the first time. It succeeded in crawling our authentication page, but the rest of the app requires to be logged in. What would be the best solution to do that?

For our E2E tests with Cypress, we have two possibilities:
* actually fill and submit the auth form
* call the login API to generate a token

The JWT is stored in localStorage.

Couldn't find any Puppeteer config to do this: https://pptr.dev/#?product=Puppeteer&version=v13.0.1&show=api-puppeteerconnectoptions

I was thinking of something like Lighthouse User Flows where we can actually control Puppeteer behavior: https://web.dev/lighthouse-user-flows/

Thanks!

**Comment by harlan-zw** [comment]
Hey @nicooprat 

Just FYI you should be unblocked on this now. Let me know if the example here works: https://unlighthouse.dev/guide/puppeteer.html#hook-into-puppeteer-navigation

Otherwise feel free to jump into the discord and happy to try and get it working with you
