### ISSUE TITLE
Running CI on Github stalls out

### ISSUE THREAD

**Issue by JDHalm** [harlan-zw/unlighthouse#30]
### Describe the bug

I'm following the CI + Github Actions example: https://unlighthouse.dev/integrations/ci.html#github-actions-netlify-example

Here's my yml:

```name: Assertions and static report

on: [pull_request]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm add @unlighthouse/cli puppeteer

      - name: Unlighthouse assertions and client
        run: npx unlighthouse-ci --urls [redacted] --debug --build-static
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy
        run: aws s3 sync [redacted] [redacted]
```

The github run stalls out and never completes yet shows no errors:
```[debug] [unlighthouse] Discovered 154 definitions and setup mock router.
[info] [unlighthouse] 1 manual URLs have been provided for scanning. Disabling sitemap and crawler.
[debug] [unlighthouse] Route has been queued. Path: `/` Name: _index.
[debug] [unlighthouse] HTML extract of `[redacted`](redacted) took `145`ms
[debug] [unlighthouse] Page has an alternative lang, ignoring `/`: [redacted]
[debug] [unlighthouse] Ignoring route `/`.
//never progresses past this step
```

### Reproduction

Set up GH Actions demo, run on PR

### System Info

```Shell
github actions
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MamlukiSn** [comment]
Getting this too with the CI instance. 
` unlighthouse-ci  `stalls from version` 0.3.30` to the latest release. It's working well on version `0.3.29`

```
› Starting Unlighthouse [Server: N/A Site: https://example.com/en/ Debug: true]                                                 unlighthouse 05:07:42
ℹ 1 manual URLs have been provided for scanning. Disabling sitemap and crawler.                                                    unlighthouse 05:07:42
› Route has been queued. Path: /en Name: en. 
```

It never progresses from the queued step.

**Comment by harlan-zw** [comment]
Hm strange, the CI is running fine to build the demo project https://github.com/harlan-zw/unlighthouse/actions/runs/3718553787/jobs/6306833563

Is it possible to provide a live reproduction?

**Comment by MamlukiSn** [comment]
Hi @harlan-zw 
I'm not able to share a live reproduction as i'm not using it in a CI CD context.
I however run some additional test and realised it stalls when the chromium binaries or chromium-browser used is version `92` and below (`92.0.4515.159` and below).  

Version `93.0.4577.63`  and above seem to be working fine.

I'm running it directly on a server using the commands documented on [https://unlighthouse.dev/integrations/ci](https://unlighthouse.dev/integrations/ci).

```

npm install -g @unlighthouse/cli puppeteer

unlighthouse-ci --site unlighthouse.dev --urls .,/guide/getting-started --output-path=./.unlighthouse/unlighthouse.dev --desktop --no-cache false --samples 5 --debug
```

**Comment by harlan-zw** [comment]
If you're still interested in a solution for this then the latest version may work a bit better. Otherwise, I'll need a reproduction site URL so I can find the issue.

Will close for now but please let me know :)
