### ISSUE TITLE
LCP - Missing from audit of page report

### ISSUE THREAD

**Issue by SchollSimon** [harlan-zw/unlighthouse#31]
### Describe the bug

Hi,

i just started using the 
`@unlighthouse/core`
module to extract core-web-vitals for several domains.

And i am not able to extract the metric
`largest-contentful-paint`

I tried it with the demo page
https://inspect.unlighthouse.dev/

and with the cli tool on my domain both with the same result.
Using page insights for one page returns the standard lighthouse report including the 
lcp value.

### Reproduction

Use demopage

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 14.58 GB / 31.59 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SchollSimon** [comment]
fixed thx Felix

**Comment by harlan-zw** [comment]
Oh yeh thanks for the issue! This has indeed been fixed
