### ISSUE TITLE
Operation not permitted (copyfile) inside of a docker container

### ISSUE THREAD

**Issue by raphaelbernhart** [harlan-zw/unlighthouse#41]
### The error
I am trying to get unlighthouse up and running in a docker container (base image -> ghcr.io/puppeteer/puppeteer:latest).

When using the `@unlighthouse/cli` package and passing the `--build-static` flag in this container I get the following error:

```
ℹ Generating static client.                                                                                                                                             unlighthouse 20:47:32
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EPERM: operation not permitted, copyfile '/usr/local/lib/node_modules/@unlighthouse/cli/node_modules/@unlighthouse/client/dist/index.html' -> '/app/.unlighthouse/index.html'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'copyfile',
  path: '/usr/local/lib/node_modules/@unlighthouse/cli/node_modules/@unlighthouse/client/dist/index.html',
  dest: '/app/.unlighthouse/index.html'
}
```

### My dockerfile / Reproduction (just run this docker image)
https://pastebin.com/xnJmKY1B

The nodejs version of the puppeteer base image is 16.

### What I tried
First I thought this is just a simple file permissions problem but I tried to change the permissions of the src folder and of the destination folder with no success.

As you can see in the dockerfile I also tried to change ownership again both of the src and dest folders (recursive) - no effect on the error message.

### Possible Solutions?
- Maybe someone can help me out with a working dockerfile with the flag --build-static passed (really needed :/)
- a different docker base image which works
- someone encountered the same or a similar error inside of a docker container
- I am not working that often with the filesystem inside of a NodeJS program so maybe this is just a common issue with node?! -> maybe add a check for the permissions of the src and dest folders?

Anyhow thanks for the help :D

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 27.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Firefox Developer Edition: 108.0
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oleghalin** [comment]
I was able to run absolutely identical to yours Dockerfile, but face issue with running chrome process.  Failed to launch the browser process!

**Comment by harlan-zw** [comment]
Hey @raphaelbernhart 

Sorry for the delay, thanks for the issue and research on it. I believe the issue is that the user within docker running the command doesn't have access to create the /var/app/.unlighthouse dir, what you could try is creating this folder and just granting all 777 to it as a test.

You can modify the output dir using providing `--root` and / or `--output-path` 

I've updated the CI to check it can create and use the folders it needs as part of the setup, so should be a little easier to debug now

**Comment by raphaelbernhart** [comment]
Hi @harlan-zw ,

thanks for the response. I tried your solution and it worked perfectly :)

Thanks a lot!
