### ISSUE TITLE
Allow to specify multiple sitemaps (and/or retrieve them from `robots.txt`)

### ISSUE THREAD

**Issue by jackdbd** [harlan-zw/unlighthouse#47]
### Clear and concise description of the problem

Big websites might have more than one sitemap.

There is a limit both for the size and for the number of URLs a `sitemap.xml` can have ([source](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#sitemap-best-practices)). And some sitemap generator or plugin can impose an even stricter limit. For example, [Yoast SEO](https://yoast.com/what-is-an-xml-sitemap-and-why-should-you-have-one/) for Wordpress sets this limit to 1000 URLs.

Also, a website could host its sitemap in a non-default location, using a name different from the standard `sitemap.xml`.
I encountered this issue when testing a website that didn't have a `sitemap.xml` in the root. I checked the `robots.txt` and saw that the website had sitemaps in the following locations:

-  /media/sitemap_product.xml
- /media/sitemap_category.xml
- /media/sitemap_additional_link.xml
- /media/sitemap_other.xml
- /media/sitemap_cms.xml

### Suggested solution

It would be nice to be able to specify an array of sitemaps. Or maybe fetch the `robots.txt` and look for all sitemaps declared there. I'm not sure if at the moment `sitemap.xml` is hardcoded.

### Additional context

Since there was no `sitemap.xml` in the website I was testing, I let unlighthouse run in crawler mode for a few minutes, but it didn't work at all.

I tried to run unlighthouse with `--debug` to see if there were any errors, but I saw none in the terminal.

**Comment by harlan-zw** [comment]
Hey @jackdbd, thanks for this detailed issue too :)

I agree that the sitemap scanning should be improved to support your suggestions.

Seems like there's another bug with the crawler if it was failing though. Is it possible to share the URL?

**Comment by jackdbd** [comment]
Here is the website I was testing: https://www.farmae.it/
