### ISSUE TITLE
Weird error when launching unlighthouse from vscode terminal

### ISSUE THREAD

**Issue by jordan-boyer** [harlan-zw/unlighthouse#51]
### Describe the bug

I have a weird issue. When i try to launch any of the unlighthouse command on vscode I get this error.

```bash
puppeteer-cluster/dist/Cluster.js:146
                throw new Error(`Unable to launch browser for worker, error message: ${err.message}`);
Error: Unable to launch browser for worker, error message: Failed to launch the browser process!
```

When i try running it on my native terminal i do not have any of those errors

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v16.17.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.0.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
Hey @jordan-boyer, thanks for the issue :)

Sorry for the delay, I likely won't look into this one. I don't use VSCode and the error is quite cryptic, likely an upstream issue with Puppeteer or Puppeteer Cluster. You can try the latest version which updates the dependency.
