### ISSUE TITLE
Globally installing @unlighthouse/cli doesn't add unlighthouse command to powershell

### ISSUE THREAD

**Issue by bux** [harlan-zw/unlighthouse#6]
OS: Windows 10
node js: 16.14.0
shell: Powershell 7.2.1 using[ fast node manager](https://github.com/Schniz/fnm)

_(I've updatet nodejs between my two issues here)_

When running `npm add -G @unlighthouse/cli` the `unlighthouse` command doesn't get added.
![image](https://user-images.githubusercontent.com/1235520/154983456-29b460e6-a381-4fae-a38e-4b5a384ec603.png)

unlighthouse binary doesn't get copied/added
![image](https://user-images.githubusercontent.com/1235520/154983585-83b02a64-fb98-4cc9-876e-33a256277eda.png)

**Comment by harlan-zw** [comment]
Hey @bux 

Thanks for trying it out and for submitting this detailed issue.

Seems like I've included the wrong instructions in the documentation.

I've updated the instructions, would you mind trying again :)

### Install Globally

```bash
npm install -g unlighthouse
# yarn global add unlighthouse
# pnpm install -g unlighthouse
```

Once installed you'll be able to use the CLI from anywhere with `unlighthouse`.

```bash
unlighthouse --site example.com
```

**Comment by bux** [comment]
Awesome. This command does the the trick :)
