### ISSUE TITLE
Option to exclude some url or maybe using regex in --urls option

### ISSUE THREAD

**Issue by Alzera** [harlan-zw/unlighthouse#61]
### Details

It would be useful to have an option to exclude specific URLs or to use regular expressions to filter which URLs are processed. 
This can be inconvenient in cases where certain pages should be skipped.

One possible solution would be to add a new command-line option, such as --exclude-urls, which would accept a comma-separated list of URLs to exclude. 
Alternatively, a regular expression could be used to match and exclude URLs based on a pattern.

**Comment by harlan-zw** [comment]
The `--exclude-urls /foo,/bar` option is now available with support for regex in 0.6.0.

Let me know if you have any issues with it.
