### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by Ratstail91** [harlan-zw/unlighthouse#62]
### Describe the bug

I tried running this on my website https://eggtrainer.com, but I received this error.

```
Error: Unable to launch browser for worker, error message: connect ECONNREFUSED 127.0.0.1:51667
    at Cluster.<anonymous> (/home/kruse/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-cluster/dist/Cluster.js:146:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/kruse/.npm/_npx/944abecbf21dfffb/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.15.0
```

My website *does* require authentication, but IDK if that is what caused this. Thanks in advance.

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    Memory: 2.47 GB / 3.72 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
```

**Comment by harlan-zw** [comment]
Hey @Ratstail91, thanks for the issue :)

I wasn't able to replicate this issue but I did notice a bug with your site in that only the home page was being scanned. Maybe you could try with the latest version and see if you still have issues.

`npx unlighthouse@0.7.1 --site eggtrainer.com`

**Comment by Ratstail91** [comment]
Hey @harlan-zw,

Same issue - it's still the same error, but a different port number.

```
Error: Unable to launch browser for worker, error message: connect ECONNREFUSED 127.0.0.1:63113
    at Cluster.<anonymous> (/home/kruse/.npm/_npx/f748e5d196c066c9/node_modules/puppeteer-cluster/dist/Cluster.js:146:23)
    at Generator.throw (<anonymous>)
    at rejected (/home/kruse/.npm/_npx/f748e5d196c066c9/node_modules/puppeteer-cluster/dist/Cluster.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
```

Thanks for getting back to me. This isn't a super urgent issue, it's more curiosity, but if it helps you out, that's awesome.

**Comment by Ratstail91** [comment]
Yes, sorry I thought I mentioned that. I'll try these solutions too.

**Comment by Ratstail91** [comment]
![image](https://github.com/harlan-zw/unlighthouse/assets/1625015/4f771d93-876e-48fe-b0e2-86989daeaed4)
Here's the full log after successfully installing google chrome into WSL. I'm not sure what's causing it.

**Comment by harlan-zw** [comment]
Please try using the latest `npx unlighthouse@0.7.5 --debug` :crossed_fingers:

 If it doesn't work you can try either providing your chrome path or disabling the system chrome, see https://unlighthouse.dev/guide/guides/chrome-dependency.

**Comment by harlan-zw** [comment]
This is now documented here https://unlighthouse.dev/guide/guides/common-errors

**Comment by Ratstail91** [comment]
It's working! Thank you very much!
