### ISSUE TITLE
CSV and excel reporters for CI

### ISSUE THREAD

**Issue by dit7ya** [harlan-zw/unlighthouse#63]
### Clear and concise description of the problem

I would like to use the results of the the Lighthouse scan in CI to automatically comment on PRs with the scores. The static HTML is great, but just having the main scores as output of the CLI program will be awesome. 

This action has some examples - https://github.com/foo-software/lighthouse-check-action

### Suggested solution

I would imagine a flag `--output-scores` that saves a `scores.json` file. For the actual implementation, I am not sure how to achieve it.

**Comment by mgifford** [comment]
I'd prefer a CSV, but whatever. Both can be good.

I like the output from https://github.com/cloudfour/lighthouse-parade

**Comment by harlan-zw** [comment]
Thanks for the references, it's a good idea

**Comment by briantully** [comment]
Great to hear that the data/scores may be exported easily, especially for those of us that may want a historical perspective when publishing new releases to see if any areas have regression in score.
In terms of the data format -- perhaps we can integrate with jq to convert from JSON to CSV, or at least mention it in the docs somewhere, as I'd expect CSV would be more flexible/useful as a reference/comparison format

**Comment by dit7ya** [comment]
Just pointing out that I have nothing against CSV and mentioned JSON just as an example format in the OP.

**Comment by mgifford** [comment]
CSV is just easier to import into a spreadsheet, which is how many of these reports are going to need to be processed. 

Great about unlighthouse-ci - when I try to run it though I get:

```
% npx unlighthouse-ci --site https://www.example.com
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/unlighthouse-ci - Not found
npm ERR! 404
npm ERR! 404  'unlighthouse-ci@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by harlan-zw** [comment]
I think there are two issues here:
1. More advanced reporters, currently we only have two, see https://unlighthouse.dev/integrations/ci#reporting. Ideally a CSV and excel format would be supported
2. A GitHub action to compare results from these reports. I haven't made a GitHub action before so i think this is a bit further out of scope and would be covered by a seperate repo. I'm guessing it would need some sort of cloud storage for the reports?

For now I've updated this issue to just cover issue 1. Feel free to make a separate issue for the GitHub action if it's more appropriate

**Comment by harlan-zw** [comment]
CSV is now supported, have moved [GitHub Action Support](https://github.com/harlan-zw/unlighthouse/issues/134) to this issue.

Please let me know you're feedback, will look to improve it.
