### ISSUE TITLE
A way to export report

### ISSUE THREAD

**Issue by iresharma** [harlan-zw/unlighthouse#65]
### Clear and concise description of the problem

It should be possible to share results amongst a team, report generation does take some time to generate especially for websites with a large number routes. 

### Suggested solution

There should be a way to export the result in a json format and pass it to the CLI to create the UI, this will save considerable amount of time for teams. I haven't seen the implementation of Unlighthouse yet, will soon check it. out and try to propose a solution in this thread.

**Comment by marloeffler** [comment]
would also like this to see, would be a huge game changer to have the reports a json

**Comment by harlan-zw** [comment]
Hey @iresharma, thanks for the issue.

Are you aware of the CI mode https://unlighthouse.dev/integrations/ci?

This has two features that could be useful:
- A JSON report is generated with all of the scores `ci-result.json`
- The `--build-static` option to generate a static self-hostable report 

Outside of these if you have any ideas on improvements would be good to hear.
