### ISSUE TITLE
Add routerPrefix to cli config

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [harlan-zw/unlighthouse#67]
### Clear and concise description of the problem

As a developer, I want to be able to set routerPrefix in the CLI so that I can set the routerPrefix to include a CI variable at build time.

### Suggested solution

Add routerPrefix as a CLI option and and apply it in whichever order we currently use for properties that have CLI and Config properties.

**Comment by harlan-zw** [comment]
Firstly, thanks for your generous sponsorship @NathanBeddoeWebDev! Really helps me out :)

This will be possible in v0.6.0 which I'll try to release today.
