### ISSUE TITLE
What license is this under

### ISSUE THREAD

**Issue by mgifford** [harlan-zw/unlighthouse#69]
### Details

Google Lighthouse is under a [Apache-2.0 license](https://github.com/GoogleChrome/lighthouse/blob/main/LICENSE) so would likely make sense that this is what the unlighthouse also follows.  That said, I didn't see anything about that in the GitHub Repo or https://unlighthouse.dev about what license it was released under.  

It should be listed in the LICENSE.txt but also the README.md should have a section pointing to it.

**Comment by tuminzee** [comment]
in the README.md it is mentioned `MIT License` does this help?

**Comment by harlan-zw** [comment]
Thanks @tuminzee! MIT is right, I may need to explore any appropriate licenses it's missing in the future though.

As far as I'm aware the package adheres to the Lighthouse usage guidelines

**Comment by NathanBeddoeWebDev** [comment]
Hey guys, pretty sure we need a copy of the MIT license in the repo if it's going to be MIT licensed. So having it copied into LICENSE or LICENSE.TXT would be required.

https://choosealicense.com/licenses/mit/

Correct me if I'm wrong here, that's how I've always interpreted the MIT license.

**Comment by mgifford** [comment]
That's generally how it is done with most open source licenses.

**Comment by tuminzee** [comment]
but it is already mentioned in the Readme file wouldn't that be enough to state the license?

**Comment by NathanBeddoeWebDev** [comment]
> but it is already mentioned in the Readme file wouldn't that be enough to state the license?

![image](https://github.com/harlan-zw/unlighthouse/assets/2762119/9f92a997-a540-4edd-9b04-73b12c89a809)
My interpretation of this is that we need the full copy of the license text.

**Comment by harlan-zw** [comment]
Sorry for the delay, this is now added.
