### ISSUE TITLE
Unclear certificate error

### ISSUE THREAD

**Issue by bux** [harlan-zw/unlighthouse#7]
OS: Windows 10
node js: 16.14.0

When using the following command, 
`unlighthouse --site https://www.apetito.de`
unlighthouse returns with a fatal certificate error.

![image](https://user-images.githubusercontent.com/1235520/155074862-d2082e9c-4507-481c-9cc4-f5e26867de8f.png)

Chrome accepts the included SSL certificate.

**Comment by harlan-zw** [comment]
Well hello again @bux 

Amazed by how many issues you're having, sorry about. On the bright side, you're getting things quite stable so thanks for that.

This commit should fix it: https://github.com/harlan-zw/unlighthouse/commit/7ed0b80f94a580717b58a03d7e29c66a60778c77

v0.2.2 is out which should hopefully work

```bash
npx unlighthouse@latest --site https://www.apetito.de
```

**Comment by bux** [comment]
Hey, no worries. I'm happy to be of help here.
And I can confirm that it's working.
