### ISSUE TITLE
[Website] Header Transparency Issue Impeding Readability During Scrolling

### ISSUE THREAD

**Issue by kud** [harlan-zw/unlighthouse#72]
## 🐛 Issue
Header transparency makes it difficult to read when scrolling.

## 🗺 Scenario
1. User opens the website.
2. User scrolls down the page.

## 👎 Actual result
The header of the website remains transparent while scrolling, which makes it difficult to read the content underneath.

## 👍 Expected result
The header should be opaque (non-transparent) when scrolling, ensuring that the content is easily readable.

**Comment by gijsdb** [comment]
I'd be happy to take on this issue if you want me to :)

**Comment by gijsdb** [comment]
My header does not go transparent like described?

**Comment by tuminzee** [comment]
@kud that is a very good observation
@gijsdb please refer to the given image, you can see the transparent header here

<img width="1509" alt="image" src="https://github.com/harlan-zw/unlighthouse/assets/58180803/e69424d0-ddb6-4140-8685-0e0f3d6864f3">

**Comment by tuminzee** [comment]
@kud I will try to make a pr for this one
what do you think about this @harlan-zw

**Comment by tuminzee** [comment]
To solve this a backdrop filter should be added which is already defined [here](https://github.com/harlan-zw/unlighthouse/blob/fb2fe2b2a6a931d8385b6cfd3d243d844125a30d/docs/components/content/AppHeader.vue#LL73C39-L73C39)

But this problem occurs because `backdrop.filter` is not defined

Approach to solve this could be to explicitly add backdropFilter with a static value, or globally define the value for this property

**Comment by tuminzee** [comment]
@kud I have raised the PR for this https://github.com/harlan-zw/unlighthouse/pull/75
I have referenced your description in the PR. Thank you for writing it precisely 👼🏼 

hope this will fix the issue

**Comment by kud** [comment]
> My header does not go transparent like described?


https://github.com/harlan-zw/unlighthouse/assets/655838/83b53f74-1345-4a30-b5cf-6762cd7a2604



Thank you @tuminzee , looks good.

**Comment by harlan-zw** [comment]
This is fixed with https://github.com/harlan-zw/unlighthouse/pull/75 :)
