### ISSUE TITLE
Lazy load images on the dashboard.

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [harlan-zw/unlighthouse#77]
### Clear and concise description of the problem

When you use unlighthouse on a website with hundreds of pages, the eager loading of all the sample images and LCP screenshots make the page load very slow.

### Suggested solution

For example, we could add loading=lazy to somewhere like
https://github.com/harlan-zw/unlighthouse/blob/fb2fe2b2a6a931d8385b6cfd3d243d844125a30d/packages/client/components/Cell/CellScreenshotThumbnails.vue#L31 and other places like it (LCP screenshot, Share Image)

Unless you have a solution for knowing whether something will load above or below the fold of the screen, then we'd probably have to accept the lazy loading of images that should be eagerly loaded, but this would still lead to a much better experience, not having to wait on the LCP for ALL images to load.

### Additional context

![image](https://github.com/harlan-zw/unlighthouse/assets/2762119/b0c278b2-510b-4e29-91f2-6c5caf1fc14a)
This is an example of a page load on a gigabit connection, let alone if you were on a sketchy connection. I feel like 3.07s is too long, and we could improve that VASTLY by just lazy loading images.

**Comment by harlan-zw** [comment]
Great idea! I've pushed up this change [here](https://github.com/harlan-zw/unlighthouse/commits/main), which will be available 0.6.0 which will be released soon.
