### ISSUE TITLE
CLI '--urls' option not parsed correctly

### ISSUE THREAD

**Issue by QuintenDegraeve** [harlan-zw/unlighthouse#8]
Greetings!

Congratulations on the public early access release. I have been playing around with it a bit and looks very promising!

In the [documentation](https://unlighthouse.dev/integrations/cli.html#cli-options) it is indicated that a `--urls` option can be passed with a _comma-seperated list_ argument. 
When executing following command `unlighthouse --site www.example.com --urls '/page-one,/page-two,/page-three'` an error will be thrown:

```
(node:31885) UnhandledPromiseRejectionWarning: TypeError: options.urls.split is not a function
    at pickOptions (file:///.../@unlighthouse/cli/dist/chunks/createCli.mjs:82:32)
    at run (file:///.../@unlighthouse/cli/dist/cli.mjs:18:8)
    at file:///.../@unlighthouse/cli/dist/cli.mjs:38:1
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31885) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31885) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It seems that currently the `options.urls` is a `boolean`, causing the code to throw the error. The issue is likely caused by the missing argument declaration in the [**cac option** for the `--urls`](https://github.com/harlan-zw/unlighthouse/blob/main/packages/cli/src/createCli.ts#L28). As of right now it doesn't include an angled (or square) brackets to indicate an argument.

Thanks!

**Comment by harlan-zw** [comment]
Hey @QuintenDegraeve 

Thank you! And thank you for this detailed issue, appreciate the effort.

You were spot on with the problem, quite obvious I didn't test that properly... :facepalm: 

Fixed in this commit: https://github.com/harlan-zw/unlighthouse/commit/96087e81162261da3e398bf54da7af4f18b27255

I'll be making an effort to setup tests for anything that isn't working like this, which should make things stable.
