### ISSUE TITLE
Getting unlighthouse to run through Docker.

### ISSUE THREAD

**Issue by simondtd** [harlan-zw/unlighthouse#81]
### Details

Is there any guide on how to get unlighthouse to work with Docker? I've been trying for the past day ish but cant get it to run. 

Here is the error im getting:
Error: Unable to launch browser for worker, error message: Failed to launch the browser process!

And here is my Dockerfile
```
FROM node:slim AS app

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
RUN npm i -g @unlighthouse/cli puppeteer
CMD npx unlighthouse-ci --site https://simonh.dev
```

**Comment by ToshY** [comment]
I just want to try out this tool but without a functional docker image it's not really feasible. Is there support for an official image on the roadmap?

**Comment by indykoning** [comment]
Maybe not exactly how you want it as you're interested in running unlighthouse-ci instead of the web frontend.
However i did manage to get unlighthouse running via docker
https://github.com/indykoning/unlighthouse-docker

i think the most important steps were the user and the `--no-sandbox` argument https://github.com/indykoning/unlighthouse-docker/blob/master/unlighthouse.config.ts#L3

**Comment by jeroensmink98** [comment]
Thanks, I was looking for something like this. Now I want to be able to stop the docker container when the scanning is finished but I cant seem to get the hooks working https://unlighthouse.dev/api/#worker-finished

**Comment by jeroensmink98** [comment]
Got it working

```js
export default {
    puppeteerOptions: {
        args: ["--no-sandbox", "--disable-setuid-sandbox"],
    },
    server: {
        open: false,
    },
    cache: false,
    hooks: {
        'worker-finished': async () => {
            process.exit(0);
        }
    }
}

```

**Comment by harlan-zw** [comment]
Thanks guys, I have added some notes about the Docker usage here from your discussions: https://unlighthouse.dev/guide/guides/docker

Let me know if you have anything to add.
