### ISSUE TITLE
False positive domain redirect detection

### ISSUE THREAD

**Issue by Maclay74** [harlan-zw/unlighthouse#83]
### Describe the bug

In our application we redirect user to a language-specific version of the page, but unlighthouse says that it's a different domain, and it's going to be ignored.

```
➜  ~ npx unlighthouse --site https://website.com/en
```
```
 WARN  Redirected URL goes to a different domain, ignoring. `https://website.com/en.       
```

So we end up with the infinite `Waiting for routes...` message without any change. 

### Reproduction

npx unlighthouse --site https://cdprojektred.com

### System / Nuxt Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 816.31 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Safari: 16.4
```

**Comment by harlan-zw** [comment]
Hey @Maclay74, thanks for the issue.

I've pushed up a fix to support subdomains that will be available in v0.6.0 which will be released today at some point.
