### ISSUE TITLE
Add support for ports

### ISSUE THREAD

**Issue by philharmonie** [harlan-zw/unlighthouse#85]
### Clear and concise description of the problem

Currently it is not possible to provide a port in the site attribute:
```
 FATAL  Request to site http://localhost:8000/ threw an unhandled exception. Please check the URL is valid. connect ECONNREFUSED ::1:8000
```

### Suggested solution

Add support to use ports as well

**Comment by harlan-zw** [comment]
Hey @philharmonie, thanks for the issue.

Can you try with v0.6.0? Otherwise I might need some further reproduction details, like what command you are using. I've tested locally and it seems to work fine with `unlighthosue --site localhost:3000`
