### ISSUE TITLE
Support for self signed certificate websites

### ISSUE THREAD

**Issue by Redirts** [harlan-zw/unlighthouse#86]
### Clear and concise description of the problem

I have a website running locally with a self-signed certificate and when unlighthouse runs it gets stuck on Chrome's prompt of "invalid" certificate:

Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CERT_AUTHORITY_INVALID)

### Suggested solution

Parameter to by pass this prompt

**Comment by harlan-zw** [comment]
Hey @Redirts, thanks for the issue.

This should be fixed in v0.6.0 which will be released shortly.
