### ISSUE TITLE
Add cookies

### ISSUE THREAD

**Issue by Impre-visible** [harlan-zw/unlighthouse#88]
### Clear and concise description of the problem

It could be cool if we were able to set cookies, for token for exemple. Cause on of my website need a cookie for all-1 pages.

### Suggested solution

So when we do : npx unlighthouse --site site.com
we could also do : npm unlighthouse --site site.com --cookies token:value,token2:value2...

**Comment by harlan-zw** [comment]
Hey @Impre-visible, thanks for the suggestion! 

This is now supported in v0.6.0. 

Let me know if you have any issues with it.

**Comment by Impre-visible** [comment]
Thanks, I'm gonna try that
