### ISSUE TITLE
Unexpected Badges on App Header

### ISSUE THREAD

**Issue by tuminzee** [harlan-zw/unlighthouse#89]
### Describe the bug

I have encountered this while scrolling the docs https://unlighthouse.dev/api/glossary/#route-definition
Github Star, Github sponsor are displayed two times
This does not happen all the time, so I don't know how to reproduce the same error

<img width="1512" alt="image" src="https://github.com/harlan-zw/unlighthouse/assets/58180803/584a118f-2c9d-4e6e-867d-ef63a8b9a29d">

### Reproduction

go to route https://unlighthouse.dev/api/glossary/#route-definition

### System / Nuxt Info

```Shell
System: MacOs
```

**Comment by harlan-zw** [comment]
Oh ye this one was solved, moved to nuxt-lego for the github stars.
