### ISSUE TITLE
[unhandledRejection] Path contains invalid characters

### ISSUE THREAD

**Issue by florian-lefebvre** [harlan-zw/unlighthouse#9]
First of all thanks for creating this project, it looks awesome!

Using Nuxt (`nuxt3@^3.0.0-27437402.494f85a`) on Windows 10, an error is thrown in the terminal:

```bash
 ERROR  [unhandledRejection] Path contains invalid characters: D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\.unlighthouse\localhost:3000\301e
```
The concerned repo is at https://github.com/florian-lefebvre/portfolio/tree/v4_nuxtjs.

**Comment by florian-lefebvre** [comment]
It seems to be working anyway but just wanted to report this

**Comment by harlan-zw** [comment]
Thanks for reporting this @florian-lefebvre, appreciate it! 

Issue should be sorted now
