### ISSUE TITLE
fetchRawUrl fails even though puppeteer sets session cookies

### ISSUE THREAD

**Issue by pocesar** [harlan-zw/unlighthouse#90]
### Describe the bug

The code in 

```js

const validateHost = async (resolvedConfig) => {
  const logger = useLogger();
  if (resolvedConfig.site) {
    logger.debug(`Testing Site \`${resolvedConfig.site}\` is valid.`);
    const { valid, response, error, redirected, redirectUrl } = await fetchUrlRaw(resolvedConfig.site, resolvedConfig);
```

forcefully tries to fetch the website without any authentication, which makes the whole process fail. 
Either provide a hook/config for setting the headers of that request or make a "skipSiteCheck: boolean" option to bypass that entirely. 

Repro:

* Set cookies using puppeteer using hooks:
```js
  hooks: {
    puppeteer: {
      "before-goto": async (page) => {
        await page.setCookie({
          name: '_vercel_jwt',
          value: VERCEL_JWT!,
          domain: parsed.host,
          path: '/',
          expires: -1,
          httpOnly: true,
          secure: true,
        })
      },
    }
  },
```
* Have any URL return anything other than 200 (like 403 or 401) for /
* Process won't start, with error `FATAL  Request to site https://some-preview-from.vercel.app/ threw an unhandled exception. Please check the URL is valid. Request failed with status code 401`

### System / Nuxt Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (6) x64 AMD Ryzen 7 5800X3D 8-Core Processor
    Memory: 14.22 GB / 15.62 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0
    Yarn: 1.22.19
    npm: 9.5.1
```

**Comment by harlan-zw** [comment]
Hey @pocesar, thanks for the issue.

I've made a couple of changes to help improve this that are available in 0.6.0.
- The scan will proceed even if the host check fails
- You can provide cookie config (https://unlighthouse.dev/guide/guides/authentication#cookies), this is passed to the axios request options

Let me know if you have any issues with it :)
