### ISSUE TITLE
PDF's aren't being ignored

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [harlan-zw/unlighthouse#96]
### Describe the bug

**Summary**
When scanning our site, I've noticed that PDF content types are still being added to the report, and failing in lighthouse. My current solution is to just include those paths in the excludedUrls config, but long term that's not ok.

I've confirmed that the paths are returning an application/pdf content type, and I can see that in https://github.com/harlan-zw/unlighthouse/blob/303344936c7fdfdbefefb3e31092cfbf74826fd0/packages/core/src/puppeteer/tasks/html.ts#L63 we should be ignoring these files, so not sure what's going on yet.

<img width="1648" alt="image" src="https://github.com/harlan-zw/unlighthouse/assets/2762119/7afb73df-98ba-40bd-9c61-55dd8dbbaf73">

### Reproduction

node packages/cli/dist/cli.mjs --site https://www.youi.com.au

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `pnpm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
Thanks @NathanBeddoeWebDev, this is fixed in 0.7.0 :)
