### ISSUE TITLE
Include a full report with a breakdown of the metrics in static export

### ISSUE THREAD

**Issue by mastoj** [harlan-zw/unlighthouse#98]
### Clear and concise description of the problem

I would really like to track my progress over time when it comes to the different metrics. Having all numbers in a json would enable me to store them somewhere to achieve exactly that.

### Suggested solution

Include all the data in ci-result.json. As of now it only contains the "score", which I think is the average of the four metrics for the page, it would be nice to have the breakdown as well. 

Something like this:

```
{
    "path": ...,
    "score": 0.88,
    "details": {
        "performance": 0.99,
        "accessibility": 0.7,
        "seo": 0.88,
        "best practice": 0.88,
    }
}
```

**Comment by harlan-zw** [comment]
Hi @mastoj, thanks for the suggestion.

When you run a static report it should save the lighthouse.json report for every scanned route, is this what you need?

**Comment by mastoj** [comment]
(First I must say it is a really cool project :) ).

I don't see a lighthouse.json file. I have set `buildStatic` to true to get a report, but the only json file I find is the "ci-result.json" file. Looking in the "reports" folder does not contain any data file. Do I need to set something in my config to get the data file?

**Comment by mastoj** [comment]
I removed the `buildStatic` and I can see the file now in each folder. It would however be nice to have the summary numbers in `ci-result.json` I think.

**Comment by mastoj** [comment]
I created a suggesion for what I think make sense. Also, making the report an object instead of an array makes it easier to add things to the report at a later point.

**Comment by mastoj** [comment]
I can just do as a do with the categories, and all that are available.
